print("========================================")
print("Mediathek Monitor")
print("========================================")
print("GitHub Actions funktioniert!")
print("Das Python-Programm wurde erfolgreich ausgeführt.")
print("========================================")
